apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voyager-frontend.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "voyager-frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.js: |
    window.REACT_APP_API_URL = "{{ .Values.config.apiUrl }}"
