{{- if .Values.app.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.envSecretName }}
spec:
  refreshInterval: {{ .Values.app.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.app.externalSecret.secretStoreRef }}
  target:
    name: {{ .Values.app.envSecretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        .env: |
          POSTGRES_USER={{ `{{ .username }}` }}
          POSTGRES_PASSWORD={{ `{{ .password }}` }}
          POSTGRES_DB={{ `{{ .database }}` }}
          POSTGRES_SERVER_HOST={{ `{{ .host }}` }}
          POSTGRES_SSL_MODE=require
          CLIENT_URL={{ .Values.app.clientUrl }}
          SERVER_PORT=8080
          JWT_KEY={{ `{{ .jwt_key }}` }}
          RUN_MIGRATION=true
  dataFrom:
    - extract:
        key: {{ .Values.app.externalSecret.remoteSecretName }}
{{- end }}
