{{- if not .Values.app.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.envSecretName }}
type: Opaque
stringData:
  .env: |
    POSTGRES_USER=postgres
    POSTGRES_PASSWORD=replace-me
    POSTGRES_DB=postgres
    POSTGRES_SERVER_HOST=replace-me
    POSTGRES_SSL_MODE=disable
    CLIENT_URL={{ .Values.app.clientUrl }}
    SERVER_PORT=8080
    JWT_KEY=replace-me
    RUN_MIGRATION=true
{{- end }}
