{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "voyager-backend.fullname" .) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "voyager-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
